# Generated by Django 3.2.4 on 2021-07-24 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_auto_20210701_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='descriptiontype',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='filetype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(max_length=30, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='contact1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
