# Generated by Django 3.2.4 on 2021-07-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210724_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact1',
            name='user',
        ),
    ]
